import ProgramCard from './ProgramCard';

const ProgramList: React.FC = () => {
    const programs = [
        { title: '‘Autumn Leaves, but Returns Every Year’ & ‘Snow-body’s Business’', description: 'These two seasonal themes talk about about the beautiful changes we see in the climate and environment as we leave the summer and things get a bit chillier. Each theme presents a dance activity, an instrument game, a dramatized storybook as well as school readiness and literacy activities to engage the children as they learn about the weather and seasons of fall and winter.' },
        { title: 'Be A Superhero Day!', description: 'Our fun and exciting superhero theme discusses what makes a superhero. We begin with a superhero accessorizing rhyme that gets the children ready to be a superhero for the day (school readiness activity involving counting money to pay for a cape, goggles, and the works). This is followed by the dramatic and musical reading of Born to Read by Judy Sierra in which we learn about a little know superhero, Sam, and how he uses his superpower of reading to save the day in the town of Sunny Skies. Afterwards, the students engage in a team-building and literacy promoting guessing game where the “it” student selected (by way of musical ‘hot potato’) reads a short clue of a famous mystery superhero. Finally, the students get up and dance as they help choreograph the Superhero Boogie based on the song “When You’re Happy and You Know It”.' },
        { title: 'Science of the Times', description: 'A creative and fun program that starts off with a musical astronomy team-building activity, Planet Roll Call, in which the students are assigned a role as the sun or a planet. Here we discuss sequence of planets, sizes, and which is furthermost and closest to our sun. Afterwords, we bring our program back to earth with a Surf and Turf categorization game where the students go on a march to seek out and organize animals according to where they live: water, land, or both (Venn Diagram style). Of course we will feature a science-based, A Strange Place to Call Home by Singer and Young.' },
        { title: '‘Count Me In!’ Mathematics', description: 'Geometry, basic equations, money management, and counting activities are made enjoyable with this mathematics educational theme. The students ‘go shopping’ and learn about various coins and bills in a shopping game. They also go on a Geometry Hunt for various shapes in our new game “Square Necessities”. Dramatized storybooks and a Simon Says Math game are other highlights of this fun program.' },
        { title: 'Slow-E-motion', description: 'A program all about learning to identify, understand, and respond positively to our emotions and feelings. This theme contains music, dance, and instrument activities designed to explore feelings like: frustration, anger, happiness, etc. One of the highlights is our creative dance piece “When You’re Grumpy and You Know It!” where the students get to put choreography to varied emotions. A Tough-Situation roll play flashcard game poses different frustrating scenarios a student may encounter during the day. As a group, we talk about how to positively respond to each scenario and be a good friend and team-player whatever the circumstances.' },
        { title: 'Verb Up!', description: '‘Verb Up!’ is all about action! This busy and kinetic lesson plan introduces the concept of verbs as action words. Each activity, including the dramatic reading of Giraffes Can’t Dance! by Giles Andreae, highlights the different verbs we use in everyday speech. The program theme also includes a creative play activity miming the different movements of animals we may see on a farm.' },
        { title: 'All About Instruments', description: 'This exciting program provides an opportunity to identify, learn about, and explore various percussion instruments, including maracas, rhythm sticks, triangles, and more. To promote team building, the children have an opportunity to participate as a member of a rhythm section. We also feature the book Farkle McBride by John Lithgow about a musically gifted boy who discovers his true passion: conducting. We then go on an ‘Instrument Treasure” hunt.' },
        { title: 'Transportation', description: 'Each activity, song, and dance features a different mode of transportation (busses, cars, and planes- oh my!). The educational concept of transportation is reinforced through fun activities like: the Traveler Hokey Pokey, a Traffic Light driving game where the children are introduced to ASL, a ‘Cho-Cho Train Dance’, and of course an age-appropriate Transportation book.' },
        { title: 'Jungle Safari', description: 'Join us as we trek through the wild jungle, searching for busy monkeys, colorful parrots, lazy sloth, giant rhinos, and exotic butterflies. This educational theme, takes us on an adventure through the vines, mud, and tall trees as we learn about the sights and sounds we might encounter on a safari. Come, let us sing, sign, rhyme, read, and dance through the heart of the jungle!' },
        { title: '‘H2Oh!’ Water Theme', description: 'This theme takes us on a trip to a small pond, teeming with life. We begin with a dance that is just ‘ducky’ and conclude with a creative finger play about five naughty little fishes. Our theme and activities are all support the selected book: Down by the Cool of the Pool by Tony Mitton or Finklehopper Frog by Irene Livingston.' },
        { title: 'Hamming It Up', description: 'Oink. These adorable and intelligent animals deserved a theme of their own. In reinforcing the concept of adjectives, we support our selected book with a fun signing finger play about different kinds of pigs. The students also learn our ‘Silly Swine Jump Rope Rhyme’; this dance activity provides the children an opportunity to help the session leader choreograph a simple dance step about five naughty little pigs.' },
        { title: 'The Seasons (One Theme Per Season)', description: 'These four separate themes bring us through the seasons: summer, winter, spring, and fall. We highlight the different and unique sights, smells, and sounds that each season brings, from the warm sunny beach days of summer, to the chilly winter days of sledding and hot chocolate.' },
        { title: 'Small Critters', description: 'This theme is all about the itty-bitty creatures. We get to join them they crawl, slither, hop, and skitter their way through our big world. Each song, dance, and signing activity illuminates the fascinating adventures of squirrels, mice, and more!' },
        { title: 'Health and Safety', description: 'How Does a Dinosaur Get Well Soon? (by Jane Yolen). This question, and many similar questions that are covered during our health and safety theme. One of the activities we feature talks about what to do in the case of an emergency with our “911” song. An onomatopoetic instrument (maracas) activity encourages proper dental care. Regular exercise becomes fun with a song and dance game!' },
        { title: 'Dinosaurs', description: 'Boom, Crash, ROAR! Come join us as we travel in time back to the Dino-Days of long ago. After learning the Dinosaur Dance, we teach the children a Compound Word Song about different dinosaur related vocabulary. We also venture into the wilds on a Safari Dino Hunt searching for various species of dinosaurs including Gallimimus, T-Rex, Brachiosaurus, and much more.' },
        { title: 'Stranger Than Fiction', description: 'Stranger Than Fiction introduces the children to the wonderful world of make-believe. This interactive and educational theme begins by playing a scavenger hunt game designed to explore the difference between fiction and non-fiction. Our “Who Are You” Alice in Wonderland question game helps the children understand the concepts of: who, what, when, where, how, and why and their role in question statements. Of course live music, dance, and dramatized storybooks are other features of this program.' },
        { title: 'We’ve Got Your Number', description: 'Geometry, basic equations, money management, and counting activities are made enjoyable with this mathematic educational theme. The students ‘go shopping’ and learn about various coins and bills in a shopping game. They also go on a Geometry Hunt for various shapes in our new game “Square Necessities”. Dramatized storybooks and a Simon Says Math game are other highlights of this fun program.' },
    ];

    return (
        <section id="programs">
            <h2>Our Programs</h2>
            <p>We tailor each lesson plan to suit the population of each classroom (Grades PK& K-3rd Grade), reinforcing 
                everything from: letters, counting, words, phonemic awareness, parts of speech, colors, metaphors, and more.</p>
            <p>The Common Core State Standards (CCSS) in English and Language Arts (ELA) is used a guide for Two Right 
                Feet Program Curriculum. And, of course, all of our themes involve dancing, creative movement, a dramatic, 
                interactive reading of a selected book, songs, signing, finger-plays, and other fun musical activities.</p>

            <div className="program-list">
                {programs.map((program, index) => (
                    <ProgramCard key={index} {...program} />
                ))}
            </div>

            <p>Other educational themes we are offering this year include: ‘A Nickel For Your Thoughts’ (All about the Five 
                Senses), Exercise Theme, ‘Don’t Bug Me!’ Insect Theme, ‘Mixed Vegetables’ Theme, Sports Theme, and ‘The Five 
                Senses’ Theme.</p>
        </section>
    );
};

export default ProgramList;
